# Generated by Django 5.1 on 2024-09-03 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthSessionState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(blank=True, max_length=255)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "galaxy_api_key",
                    models.CharField(blank=True, max_length=128),
                ),
                ("refresh_token", models.CharField(blank=True, max_length=255)),
                ("session_type", models.CharField(blank=True, max_length=32)),
                ("state_param", models.CharField(blank=True, max_length=128)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
