# Generated by Django 5.2 on 2025-06-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(blank=True, default=False)),
                ('message', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
